### ISSUE TITLE
Problem with the punctuation rule

### ISSUE THREAD

**Issue by rosieyohannan** [ChrisChinchilla/Openly#24]
`\b(?:eg|ie)[^,]: eg, or ie,` is picking up words like "egress" and suggesting I change to eg

**Comment by ChrisChinchilla** [comment]
@rosieyohannan You're right, though to be honest when I look at the rule, the whole thing doesn't make sense to me, why replace "e.g. with eg"? So for now, I might just remove it and it back later.
