### ISSUE TITLE
`.github/workflows/todo-issue.yml / build (push) Successful in 6s` check could be more readable

### ISSUE THREAD

**Issue by hamirmahal** [ChrisChinchilla/Openly#27]
`.github/workflows/todo-issue.yml / build (push) Successful in 6s` could be more human-readable.

**Comment by hamirmahal** [comment]
![image](https://github.com/user-attachments/assets/0f84a32d-7931-492c-af7c-e2e21cade4c2)

**Comment by ChrisChinchilla** [comment]
Thanks @hamirmahal but this is just an internal workflow that only I use.

**Comment by hamirmahal** [comment]
You're welcome @ChrisChinchilla.
